### ISSUE TITLE
HanziGraph

### ISSUE THREAD

**Issue by batterseapower** [batterseapower/pinyin-toolkit#20]
Port the code from Kanji Graph plugin into this plugin [adds a graph showing how many unique hanzi in deck over time](can't simply change fields, uses Japanese specific functions)

**Comment by Nick3C** [comment]
This should be quite high priority really. It should be relatively easy to do but will give a major improvement immediately.

**Comment by batterseapower** [comment]
I've massaged the code so it's rather better, but I can't get the hook to fire. Need to find time to look into this one.

**Comment by batterseapower** [comment]
Get the Hanzi graph working. Closed by 014ae8a045364ee68697383e7c01a43659809d23

**Comment by Nick3C** [comment]
Sorry mate, the graph isn't working for me. It is called correctly and appears (with the right scale and so on) but is blank.

**Comment by batterseapower** [comment]
I'm sure this works :-). However, it only works on decks with a Manadarin tag, so I've added some code so we don't display the graph in that case. If that doesn't show your problem, you could try increasing the # of days displayed?

**Comment by Nick3C** [comment]
Yup, I have treid that before posting. It really doesn't work I'm afraid.

It could be somehting to do with my complex deck arrangements (multiple models with "mandarin" in them or something similar).

Could you send me your working deck and I will see if I can break it ^___^ (perhaps delete all but a few cards and optimise db then zip it first so that it is small).

**Comment by batterseapower** [comment]
Hmm. I've sent you a deck via email to try.

**Comment by Nick3C** [comment]
Ok, sussed it out thanks to your deck (which works). The answer is that I have multi-model decks and so must use something other than "Mandarin" as a model name. I use tags in the format of "[M]-Vocab Mandarin" where M stands for model and vocab is the name.

Changing my main vocab model to Mandarin solves the problem (but obviously means I don't get data for my other models.

The solution is to search for decks containing "mandarin" in the model but not being equal to "mandarin"

**Comment by batterseapower** [comment]
Sweet. I've pushed the fix to my fork.

**Comment by Nick3C** [comment]
Hm, sorry, that hasn't got it. I can get the graphs by changing the model tag to Mandarin but still doesn't work if model tag is "[M]-Vocab Mandarin".

I tried using my tag of "[M]-Vocab Mandarin" on your test deck but that didn't work either... nor did "Vocab Mandarin"

**Comment by batterseapower** [comment]
I changed my tags to "Vocab Mandarin" and it works fine for my test deck. What revision are you using?

**Comment by Nick3C** [comment]
Ah, right you are then, graph displays now (though quite a few issues reported in other thread.
